import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" /> */}
      </Head>

      <main>
        <h1>Hello Word</h1>
      </main>
    </>
  );
}
